### ISSUE TITLE
prov label strings and qualified names

### ISSUE THREAD

**Issue by heatherpacker** [lucmoreau/ProvToolbox#104]
Using the provtoolbox to convert the following into provn:

document
  prefix cas <http://smartsociety-project.github.io/cas/#>
  prefix var <http://openprovenance.org/var#>

    entity(var:view, [prov:type='cas:View', prov:label='cas:View'])
endDocument

produces:

document
prefix cas <http://smartsociety-project.github.io/cas/#>
prefix xsd <http://www.w3.org/2001/XMLSchema>
prefix var <http://openprovenance.org/var#>
entity(var:view,[prov:type = 'cas:View', prov:label = "'cas:{http://smartsociety-project.github.io/cas/#}View'"])
endDocument

Prov DM says that labels only supports strings, so should this create an error.  Will labels be able to support qualified names in the future?

**Comment by lucmoreau** [comment]
You need to provide a string. No plan to support qualified names.



On 05/02/2015 12:42, heatherpacker wrote:
>
> Using the provtoolbox to convert the following into provn:
>
> document
> prefix cas http://smartsociety-project.github.io/cas/#
> prefix var http://openprovenance.org/var#
>
> |entity(var:view, [prov:type='cas:View', prov:label='cas:View'])
> |
>
> endDocument
>
> produces:
>
> document
> prefix cas http://smartsociety-project.github.io/cas/#
> prefix xsd http://www.w3.org/2001/XMLSchema
> prefix var http://openprovenance.org/var#
> entity(var:view,[prov:type = 'cas:View', prov:label = 
> "'cas:{http://smartsociety-project.github.io/cas/#}View 
> <http://smartsociety-project.github.io/cas/#%7DView>'"])
> endDocument
>
> Prov DM says that labels only supports strings, so should this create 
> an error. Will labels be able to support qualified names in the future?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lucmoreau/ProvToolbox/issues/104>.Web Bug from 
> https://github.com/notifications/beacon/AAIrw0l8n8Z9pPNEU8jk8tis_gI1jvlNks5no1zDgaJpZM4DcKVY.gif
>

-- 
Professor Luc Moreau
Head of the Web and Internet Science Group
Electronics and Computer Science   tel:   +44 23 8059 4487
University of Southampton          twitter: @lucmoreau
Southampton SO17 1BJ, UK           http://www.ecs.soton.ac.uk/~lavm

**Comment by lucmoreau** [comment]
There is now a warning printed by provconvert in this situation.

14:46:46,731  WARN ProvFactory:147 - label value is not a string 'cas:{http://smartsociety-project.github.io/cas/#}View'

**Comment by lucmoreau** [comment]
Created a new issue to handle strict mode.
#137
