### ISSUE TITLE
Bundle: turtle to prov-n conversion

### ISSUE THREAD

**Issue by cmaumet** [lucmoreau/ProvToolbox#107]
Hello,

I am looking for some advice to interpret the following  [example](http://www.w3.org/TR/2013/REC-prov-o-20130430/#Bundle) from the PROV-O specification (bundle serialisation in RDF). 

In particular, I am wondering if, in this example: 
 1. `:report1` is part of the bundle defined in `http://www.example.com/example.ttl` **or**;
 2. `:report1` is a separate entity, not necessarily related to the bundle?

```
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix my:      <http://example.com/my#> .
@prefix :        <http://example.com/#> .
@base <http://www.example.com/example.ttl> .

<> # A provenance file located at http://www.example.com/example.ttl
   a prov:Bundle;
   prov:generatedAtTime "2012-05-24T09:30:00"^^xsd:dateTime;
   prov:wasAttributedTo :bob;
.

:report1
   a my:Report, prov:Entity;
   my:version "1";
   prov:generatedAtTime "2012-05-24T01:00:00"^^xsd:dateTime;
   prov:wasAttributedTo :bob;
.
```

Using `provconvert`, this example is converted in prov-n to:
```
document
  prefix pre_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  prefix bnode <http://openprovenance.org/provtoolbox/bnode/>
  prefix xsd <http://www.w3.org/2001/XMLSchema>
  prefix pre_0 <http://www.example.com/>
  prefix def <http://example.com/#>
  prefix my <http://example.com/my#>
  
  entity(def:report1,[prov:type = 'my:Report', my:version = "1" %% xsd:string])
  entity(pre_0:example.ttl,[prov:type = 'prov:Bundle'])
  wasAttributedTo(def:report1, def:bob)
  wasAttributedTo(pre_0:example.ttl, def:bob)
endDocument
```
which seems to indicate that `:report1` is not necessarily part of the bundle?

I would be grateful of any feedback or, if this discussion is out of the scope of the ProvToolbox, if you could point me to a more appropriate contact to discuss this issue. Thank you in advance.

**Comment by stain** [comment]
<> in Turtle means the file itself, which also declares :report1

so you are right in that this should be part of the bundle.

**Comment by lucmoreau** [comment]
Hello,

I am not sure what you mean by being part of the bundle, and that :report1 is not necessarily part of the bundle.

1. I suspect that you mean the URI referenece :report1 does not occur in the bundle.

2. While the term
  entity(pre_0:example.ttl,[prov:type = 'prov:Bundle'])
  asserts resource with uri pre_0:example.ttl to be of type Bundle,
  PROV is explicitly non normative about what you should expect when you dereference a bundle URI.

3.  In our book, Paul and I suggested that when we dereference such a bundle URI, we get a named graph.

4. Turtle does not have a named graph representation, by which you could say that there is URI reference "in" a bundle or not.

5. Instead, you should use trig

@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix pre_1: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix bnode: <http://openprovenance.org/provtoolbox/bnode/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix pre_0: <http://www.example.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix def: <http://example.com/#> .
@prefix my: <http://example.com/my#> .


my:bun {
	def:report1 a prov:Entity , my:Report ;
		my:version "1"^^xsd:string .	
	<http://www.example.com/example.ttl> a prov:Entity , prov:Bundle .	
	def:report1 prov:wasAttributedTo def:bob .	
	<http://www.example.com/example.ttl> prov:wasAttributedTo def:bob .
}

 6. This would correspond to the prov-n document:

document
  prefix pre_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  prefix xsd <http://www.w3.org/2001/XMLSchema>
  prefix pre_0 <http://www.example.com/>
  prefix def <http://example.com/#>
  prefix my <http://example.com/my#>
  bundle my:bun
      entity(def:report1,[prov:type = 'my:Report', my:version = "1" %% xsd:string])
      entity(pre_0:example.ttl,[prov:type = 'prov:Bundle'])
      wasAttributedTo(def:report1, def:bob)
      wasAttributedTo(pre_0:example.ttl, def:bob)
  endBundle
endDocument

**Comment by cmaumet** [comment]
Thank you very much for your replies. 

Maybe to clarify my request, I should have said that I was wondering what would be the equivalent in turtle of a provn document containing `bundle`/`endBundle` statements. 

@lucmoreau: if I understood correctly, you are suggesting that, strictly-speaking, there is no such equivalent in turtle but that we could use trig instead (with a named graph)?

**Comment by lucmoreau** [comment]
Yes, the prov recommendations have not defined a mapping between the various representations.

Informally, we said named graphs can be used to express bundles (but there may be other ways). But for this, you need to use trig.

**Comment by cmaumet** [comment]
Thank you: this is all clear for me now! I think this issue can be closed.
