### ISSUE TITLE
prov-n qnames / templates

### ISSUE THREAD

**Issue by dtm** [lucmoreau/ProvToolbox#109]
provconvert/ProvToolbox seems to have issues with specifying qname literals as
"foo:bar" %% prov:QualifiedName in provn. See the template and binding at:
   https://gist.github.com/dtm/5927338044515af518f4

var:btype does not get expanded nor is the endtime on the activity filled in.

**Comment by lucmoreau** [comment]
The fix with qualified names now addresses this issue. I added the example (with the proper capitalisation of prov:QUALIFIED_NAME) and it expands properly. See: https://github.com/lucmoreau/ProvToolbox/commit/ca453c3ed32c4280fe8d4a4d795c0a6c0942bcb8

I will close this issue.
