### ISSUE TITLE
parsing attributes in provn

### ISSUE THREAD

**Issue by dtm** [lucmoreau/ProvToolbox#111]
The provn parser accepts a document in which an attribute list is missing either or both of their [ ] characters. Eg

document
prefix ex <http://example.com/>
entity(ex:a, ex:b='ex:c')
endDocument

It does warn, however.

**Comment by lucmoreau** [comment]
Test case:

curl https://gist.githubusercontent.com/lucmoreau/056a7caeef23f1d8f65c/raw/402760acbd5544983540896c70364a79933e631e/gistfile1.txt | provconvert -infile - -informat provn -outfile - -outformat provn

**Comment by lucmoreau** [comment]
The following commit redirects the parser warnings to the log4j logging infrastructure.

https://github.com/lucmoreau/ProvToolbox/commit/71f8acccad1f1810af75a66e3e6f049873205f3d

**Comment by lucmoreau** [comment]
The question is whether does should be a warning or whether it should be a fatal reporting?

**Comment by lucmoreau** [comment]
Created a new issue to handle strict mode.
https://github.com/lucmoreau/ProvToolbox/issues/137
