### ISSUE TITLE
prov-n internationalized string incorrectly serialized

### ISSUE THREAD

**Issue by lucmoreau** [lucmoreau/ProvToolbox#133]
prov-n internationalized strings are currently serialized as

"un lieu"@fr %% prov:InternationalizedString

instead of 

"un lieu"@fr 

The type prov:InternationalizedString is the type for such strings in the xml serialization. It is also how
the ProvToolbox encodes the types of such strings internally. It should not be exposed in the prov-n representation.

I don't know how this bug this affects the json serialization.

**Comment by trungdong** [comment]
I don't think it have any impact on prov-json as I'm checking the Java type of the value (whether it is a `LangString`) before encoding it as an international string.

**Comment by lucmoreau** [comment]
There is probably a change required to the prov-json spec to explain how to serialise internationalized strings.

Professor Luc Moreau
Electronics and Computer Science
University of Southampton
Southampton SO17 1BJ
United Kingdom


On 13 Jul 2015, at 17:04, Dong Huynh <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think it have any impact on prov-json as I'm checking the Java type of the value (whether it is a LangString) before encoding it as an international string.

�

**Comment by trungdong** [comment]
[PROV-JSON](http://www.w3.org/Submission/2013/SUBM-prov-json-20130424/#data-typing) says:

> if the xsd:string value has a language tag, the literal must be represented in a JSON object as specified above, the language tag in the lang property and the type property omitted.

It looks like I should remove those `prov:InternationalString` added in the JSON outputs.

**Comment by lucmoreau** [comment]
I think that an xsd:string cannot have a language tag since it is a XML simple type.

Professor Luc Moreau
Electronics and Computer Science
University of Southampton
Southampton SO17 1BJ
United Kingdom

On 13 Jul 2015, at 23:06, Dong Huynh <notifications@github.com<mailto:notifications@github.com>> wrote:


PROV-JSON<http://www.w3.org/Submission/2013/SUBM-prov-json-20130424/#data-typing> says:

if the xsd:string value has a language tag, the literal must be represented in a JSON object as specified above, the language tag in the lang property and the type property omitted.

It looks like I should remove those prov:InternationalString added in the JSON outputs.

�

**Comment by lucmoreau** [comment]
Original issue is now addressed in development branch. Prov-json issue is outstanding.
