### ISSUE TITLE
ProvTranslator doesn't recognize `prov:specialisationOf`

### ISSUE THREAD

**Issue by binfalse** [lucmoreau/ProvToolbox#135]
The ProvTranslator seems to ignore `prov:specialisationOf`. Consider for instance:

```
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix : <#> .

:a a prov:Entity.
:b a prov:Entity.
:b prov:specialisationOf :a.
```

If I convert that I end up with just two entities and no connection. No matter which is the target language. Am I doing something wrong?
I tried that at https://provenance.ecs.soton.ac.uk/validator/view/translator.html, but also used the `toolbox/target/appassembler/bin/provconvert` built from this source.

**Comment by lucmoreau** [comment]
Hello,

There seems to be a typo: you need to use the American spelling specializationOf.
The converter works ok then.

Luc

On 19 Jul 2015, at 22:22, Martin Scharm <notifications@github.com<mailto:notifications@github.com>> wrote:


The ProvTranslator seems to ignore prov:specialisationOf. Consider for instance:

@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix : <#> .

:a a prov:Entity.
:b a prov:Entity.
:b prov:specialisationOf :a.


If I convert that I end up with just two entities and no connection. No matter which is the target language. Am I doing something wrong?
I tried that at https://provenance.ecs.soton.ac.uk/validator/view/translator.html, but also used the toolbox/target/appassembler/bin/provconvert built from this source.

�

**Comment by binfalse** [comment]
oh yeah. m(
thanks for the hint!
