### ISSUE TITLE
MacOS 0.7.2 installer not working

### ISSUE THREAD

**Issue by ericstephan** [lucmoreau/ProvToolbox#150]
https://github.com/lucmoreau/ProvToolbox/wiki/Installation#3-installing-binary-release
 http://openprovenance.org/java/installer/provconvert-0.7.2.dmg

An error was occurred when attempting to install the MacOS Binary on Mavericks (10.9.5) complaining that the installation package has been damaged. 

The error message states: "provconvert-0.7.2-Installer" is damaged and can't be opened.  You should eject the disk image.

**Comment by lucmoreau** [comment]
Hi Eric,

I think it's is a problem with the Java configuration.

In a terminal,
cd /Volumes/provconvert/
./provconvert-0.7.2-Installer.app/Contents/MacOS/JavaApplicationStub

works for me, with:

java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Does it work for you?

Luc


On 15/06/2016 12:58, Eric Stephan wrote:
>
> https://github.com/lucmoreau/ProvToolbox/wiki/Installation#3-installing-binary-release
> http://openprovenance.org/java/installer/provconvert-0.7.2.dmg
>
> An error was occurred when attempting to install the MacOS Binary on 
> Mavericks (10.9.5) complaining that the installation package has been 
> damaged.
>
> The error message states: "provconvert-0.7.2-Installer" is damaged and 
> can't be opened. You should eject the disk image.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/lucmoreau/ProvToolbox/issues/150>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe/AAIrw7nBKWzCwv7Aldx5hTaCdzR0Srcdks5qL-jmgaJpZM4I2R71>.Web 
> Bug from 
> https://github.com/notifications/beacon/AAIrw7l0mjPorh0YRcV9V0hGzdTOgrnzks5qL-jmgaJpZM4I2R71.gif
>

-- 
Professor Luc Moreau
Head of the Web and Internet Science Group
Electronics and Computer Science   tel:   +44 23 8059 4487
University of Southampton          twitter: @lucmoreau
Southampton SO17 1BJ, UK           http://www.ecs.soton.ac.uk/~lavm

**Comment by ericstephan** [comment]
Luc,

Thank you so much for your fast response to my question.  Yes the installation worked!   I am receiving an error (see below) that may have to do with the current version of Java (1.8.0_25) I am using, after updating Java I'll let you know if fixed my problem.

Kind regards,

Eric

Error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openprovenance/prov/interop/CommandLineArguments : Unsupported major.minor version 51.0

Java Version:
localhost:MacOS $ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
