### ISSUE TITLE
Issue with IndexedDocument.getAgent(String name) ? 

### ISSUE THREAD

**Issue by exas** [lucmoreau/ProvToolbox#162]
At one of my projects i try to use IndexedDocument to extend an existing document.

Agents, Activities, Entities and other elements are saved in HashMaps at IndexedDocument.
For example the Agents are saved in _agentMap_ using QualifiedName as Key:
`
private HashMap<QualifiedName,Agent>    agentMap=new HashMap<QualifiedName, Agent>();
`

The corresponding getter functions for these elements seem to be not correctly implemented, e.g. _getAgent(String name)_ at IndexedDocument:
`
public Agent getAgent(String name) {
        return agentMap.get(name);
    }
`

Shouldn't it be _getAgent(QualifiedName name)_ to be working correctly, otherwise _agentMap.get(name)_ will not work correctly with the _String name_ as the hashcode will not be the same for the HashMap lookup for QualifiedName Objects.

**Comment by Panterkoo** [comment]
I ran into this issue as well, I need to retrieve an entity and this getter method would be exactly what I'm looking for but I keep getting errors that the return value is null. (Probably because of what is mentioned here)
