### ISSUE TITLE
Tutorials do not work with new versions of ProvToolbox 0.9.5

### ISSUE THREAD

**Issue by sopeter** [lucmoreau/ProvToolbox#189]
I run into this issue while trying to run the first tutorial from the ProvToolbox repo which seems like it is trying to read the README file.
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-3:single (make-assembly) on project ProvToolbox-Tutorial1: Failed to create assembly: Error adding file to archive: Failed to read filesystem attributes for: /Users/peterso/Gilded '22/ProvToolbox/modules-tutorial/tutorial1/target/classes/README.txt -> [Help 1]

**Comment by lucmoreau** [comment]
tutorials zip archived are now tested (i.e. expanded and executed as part of the build).
