### ISSUE TITLE
Activities with the same identifier are not merged correctly

### ISSUE THREAD

**Issue by trungdong** [lucmoreau/ProvToolbox#197]
Two activity records in separate provenance documents have the same identifier, one with startTime and the other with endTime:
- `test-activity-1.provn`:
```
document
  prefix act <http://example.org/act/>
  activity(act:executing/1, 2022-06-21T14:42:12.898+01:00, -)
endDocument
```
- `test-activity-2.provn`:
```
document
  prefix act <http://example.org/act/>
  activity(act:executing/1, -, 2022-06-21T14:42:13.186+01:00)
endDocument
```
Merging the two documents, I expect to see one activity record with both time values present:
```bash
ls test-activity-*.provn | provconvert -merge - -outfile merged-activity.provn
```
However, the merge activity only has the startTime, not the endTime:
`activity(act:executing/1,2022-06-21T14:42:12.898+01:00,-)`
(the actual output from the above command line)

**Comment by lucmoreau** [comment]
updated merge functionality ofr startTime, endTime (in activities) and value (in entities).

When more than one startTime is provided, non determinist behaviour, as only one is permitted. (Ditto for endTime and value).

**Comment by lucmoreau** [comment]
Code is in the development branch, will be integrated in next release.
