### ISSUE TITLE
provide RPM packages for binary install of v >= 0.9.1

### ISSUE THREAD

**Issue by pohutukawa** [lucmoreau/ProvToolbox#206]
Hi Luc,

it seems like there are no RPM packaged versions of `provconvert` available for any versions newer than 0.9.0. However, the documentation points towards the ability of doing a `rpm` install. A bit baffling, as the Debian/Ubuntu packages are there and working.

Cheers,
Guy

**Comment by lucmoreau** [comment]
Hi Guy,

I will investigate this WE why the rpm version is not being built. In the meantime, feel free to use the zip binary archive:
https://repo1.maven.org/maven2/org/openprovenance/prov/provconvert/0.9.28/provconvert-0.9.28-release.zip

Kind regards

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/



From: Guy Kloss ***@***.***>
Date: Wednesday, 17 May 2023 at 04:00
To: lucmoreau/ProvToolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lucmoreau/ProvToolbox] provide RPM packages for binary install of v >= 0.9.1 (Issue #206)

Hi Luc,

it seems like there are no RPM packaged versions of provconvert available for any versions newer than 0.9.0. However, the documentation points towards the ability of doing a rpm install. A bit baffling, as the Debian/Ubuntu packages are there and working.

Cheers,
Guy

**Comment by pohutukawa** [comment]
Hi Luc,

much appreciated. I had already for now pivoted in our container's `Dockerfile` to use the binary ZIP, it's just more cumbersome but works for us. So it's not a show stopper, but more of an inconvenience (especially as it contradicts the binary install documentation).

Cheers,

Guy

**Comment by lucmoreau** [comment]
Hi Guy,


Please checkout https://repo1.maven.org/maven2/org/openprovenance/prov/provconvert/0.9.29/provconvert-0.9.29.rpm

Kind regards,
Luc

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/



From: Guy Kloss ***@***.***>
Date: Wednesday, 17 May 2023 at 23:11
To: lucmoreau/ProvToolbox ***@***.***>
Cc: Luc Moreau ***@***.***>, Comment ***@***.***>
Subject: Re: [lucmoreau/ProvToolbox] provide RPM packages for binary install of v >= 0.9.1 (Issue #206)

Hi Luc,

much appreciated. I had already for now pivoted in our container's Dockerfile to use the binary ZIP, it's just more cumbersome but works for us. So it's not a show stopper, but more of an inconvenience (especially as it contradicts the binary install documentation).

Cheers,

Guy
