### ISSUE TITLE
compiling latest git version fails at prov-rdf

### ISSUE THREAD

**Issue by satra** [lucmoreau/ProvToolbox#44]
on osx 10.8.2 

[ERROR] Failed to execute goal on project prov-rdf: Could not resolve dependencies for project org.openprovenance.prov:prov-rdf:jar:0.0.3-SNAPSHOT: The following artifacts could not be resolved: org.openprovenance.prov:prov-n:jar:tests:0.0.3-SNAPSHOT, org.openprovenance.prov:prov-xml:jar:tests:0.0.3-SNAPSHOT: Failure to find org.openprovenance.prov:prov-n:jar:tests:0.0.3-SNAPSHOT in http://repo.aduna-software.org/maven2/releases was cached in the local repository, resolution will not be reattempted until the update interval of aduna-opensource.releases has elapsed or updates are forced -> [Help 1]

**Comment by sid-thakur** [comment]
Hi, 
I am trying to use ProvToolbox0.4.0 but am failing to build prov-xml due to error below. I can't seem to find repositories for 0.4.0 at [http://mvnrepository.com/artifact/org.openprovenance.prov](http://mvnrepository.com/artifact/org.openprovenance.prov). I am using default pom.xml that came with ProvToolbox source code. 
Thanks. 
Sid
---
```
[provtoolbox0.4.0/prov-xml]$ sudo mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PROV-XML 0.4.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.024s
[INFO] Finished at: Tue Jul 21 14:41:14 EDT 2015
[INFO] Final Memory: 5M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project prov-xml: Could not resolve dependencies for project org.openprovenance.prov:prov-xml:jar:0.4.0: Failed to collect dependencies for [org.openprovenance.prov:prov-model:jar:0.4.0 (compile), javax.xml.bind:jaxb-api:jar:2.2.4 (compile), org.jvnet.jaxb2_commons:runtime:jar:0.4.1.5 (compile), commons-collections:commons-collections:jar:3.2.1 (compile), log4j:log4j:jar:1.2.17 (compile), junit:junit:jar:4.11 (test)]: Failed to read artifact descriptor for org.openprovenance.prov:prov-model:jar:0.4.0: Failure to find org.openprovenance.prov:ProvToolbox:pom:0.4.0 in http://download.java.net/maven/2 was cached in the local repository, resolution will not be reattempted until the update interval of maven2-repository.dev.java.net has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by lucmoreau** [comment]
Hi,
The latest is 0.6.2, whereas you are trying to compile 0.4.0.
You need to check out the latest version. Only 0.6.2 and 0.6.1 can
be found in maven central.
Luc

**Comment by sid-thakur** [comment]
@lucmoreau Thanks; But a project I am using depends on 0.4.0, is it still possible to link to that through maven?

**Comment by lucmoreau** [comment]
No, the maven artefacts were not published then. 

You will need to recompile the whole source tree, starting from the root, and not from the subproject prov-xml

Luc

**Comment by lucmoreau** [comment]
Btw, I really advise to upgrade!

**Comment by sid-thakur** [comment]
Cool, thanks for the updates.
