### ISSUE TITLE
Feature: prov-n to show prov:value attribute

### ISSUE THREAD

**Issue by stain** [lucmoreau/ProvToolbox#71]
If I convert PROV-N:

    prefix foaf <http://xmlns.com/foaf/0.1/>
    entity(input, [ prov:value="Alice", foaf:name="Fred" ])

to SVG, then I do get to see the foaf:name attribute in the output (yay!) - but strangely not the prov:value. Is this because any prov: attribute is stripped out? It would be very useful to see the values rendered as well.

**Comment by lucmoreau** [comment]
This issue is now addressed in development branch
